version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork
  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - mongodb
  client:
    build: ./client
    ports:
      - "5137:5173"
    networks:
      - mynetwork
    depends_on:
      - server
networks:
  mynetwork:
    driver: bridge
